<?php

declare(strict_types=1);

namespace SustainableWebAnalyzer;

/**
 * Grid carbon intensity of the servers a page is loaded from.
 *
 * The countries come from the ipinfo.io lookups the analysis does anyway, so no extra API call is needed.
 * The intensities are yearly country averages from Our World in Data, bundled in data/grid-intensity.php and
 * regenerated by bin/update-grid-intensity (latest year per country). A live API (e.g. the paid real-time
 * data of Electricity Maps) would not make the estimate better: results are cached for a
 * week and represent an average visit, not a single moment.
 *
 * Limits: the country of an IP is not always the grid of the data center (large countries such as the
 * US have regional grids), and CDN/anycast addresses resolve to the edge closest to the analyzer.
 */
final class GridIntensity
{
    public const SOURCE = 'Our World in Data (Ember, Energy Institute), CC BY 4.0';

    /** @var array<string, int|float>|null */
    private static ?array $countries = null;

    /**
     * g CO2e/kWh of a country, or null if the country is unknown or has no data.
     */
    public static function country(?string $countryCode): int|float|null
    {
        self::$countries ??= require dirname(__DIR__) . '/data/grid-intensity.php';

        return $countryCode === null ? null : (self::$countries[$countryCode] ?? null);
    }

    /**
     * Byte-weighted grid intensity of all servers. Bytes from servers without a known intensity
     * count with the global average.
     *
     * @param array<string, int> $bytesByCountry ISO country code (or "" for unknown) => bytes
     */
    public static function dataCenter(array $bytesByCountry): float
    {
        $bytes = array_sum($bytesByCountry);
        if ($bytes < 1) {
            return (float) Co2::GLOBAL_GRID_INTENSITY;
        }

        $weighted = 0.0;
        foreach ($bytesByCountry as $country => $countryBytes) {
            $weighted += $countryBytes * (self::country((string) $country) ?? Co2::GLOBAL_GRID_INTENSITY);
        }

        return $weighted / $bytes;
    }
}
